# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WoowahanFresh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WoowahanFresh

pod 'Alamofire'
pod 'FSCalendar'

#pod 'lottie-ios'
#pod 'SwiftLint'
#pod 'RxSwift'

pod 'FacebookCore'
pod 'FacebookLogin'
#pod 'FacebookShare'

#pod 'FBSDKCoreKit'  
#pod 'FBSDKLoginKit'
#pod 'FBSDKShareKit'

# pod 'FBSDKPlacesKit'
# pod 'FBSDKMessengerShareKit'

end

